### PR TITLE
Add docs for listing webhooks

### PR DESCRIPTION
**Pull request by n7studios**
Whilst working on [this PR for the PHP SDK](https://github.com/ConvertKit/ConvertKitSDK-PHP/pull/48), I spotted that there's an [API endpoint to list registered webhooks](https://github.com/ConvertKit/convertkit/blob/main/app/controllers/api/v3/automations/hooks_controller.rb#L24-L26), although I couldn't find this in the API docs.

Thanks!

### CODE REVIEW

**Comment by brendancarney** [comment]
Ah, no, we don't have to. @n7studios was updating our PHP SDK and noticed this was undocumented, but I didn't realize it was for a specific use case.

**Comment by n7studios** [comment]
@bradpauly @brendancarney So this isn't implemented in the current published PHP SDK version (0.1), but I added the `get_webhooks()` [function](https://github.com/ConvertKit/ConvertKitSDK-PHP/pull/48/files#diff-af24df06d08654170d9ba64fbb7b4b12edfe889e0f665d203a554f9b1e2dbf1aR830) to our upcoming 1.0 release that's due at the end of March.  This can easily be removed if you prefer, as it's not yet published.

**Comment by bradpauly** [comment]
@n7studios I'd remove it. Are you using the webhooks somehow?

**Comment by n7studios** [comment]
@bradpauly I'm not using them. The work I'm doing on the PHP SDK is to fix some existing bugs we have, and add in missing functions for documented API features, such as custom fields, updating a subscriber and so on. I'll remove the `get_webhooks()` function. Thanks!

**Pull request closed without merging**
